GFX: Fix compilation error.
BZ: 129230

Prototype of intel_scu_ipc_iowrite8 had been moved to asm/intel_scu_pmic.h.

Change-Id: Ife4f02e00f3305d5fadceb2e4fc0fe91d4a9e4fb
Signed-off-by: Fei Yang <fei.yang@intel.com>
Reviewed-on: http://android.intel.com:8080/124226
Reviewed-by: Stimson, Dale B <dale.b.stimson@intel.com>
Reviewed-by: Ernst, Eric <eric.ernst@intel.com>
Tested-by: Ranostay, Matt <matt.ranostay@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Tested-by: cactus <cactus@intel.com>